### ISSUE TITLE
github pages link broken

### ISSUE THREAD

**Issue by doktordirk** [CureApp/loopback-promised#10]
the link in the readme doesn't work
``´
[latest API documentation Page](http://cureapp.github.io/loopback-promised/doc/index.html)

```
```

**Comment by shinout** [comment]
Thanks for report!
Here is the correct URL.
http://cureapp.github.io/loopback-promised/index.html

I'll fix README soon.

**Comment by doktordirk** [comment]
that was quick. tx

**Comment by shinout** [comment]
fixed the link and I'll close the issue.
